#!/usr/bin/env python3
"""Export numerical supplementary tables from completed reports; no model fitting."""
from pathlib import Path
import csv,json,math
ROOT=Path(__file__).resolve().parents[2]
HERE=Path(__file__).resolve().parent
ANALYSIS=ROOT/'outputs/analysis'
TOPIC_LABELS=['TIMP1/COL3A1', 'JUNB/DNAJB1', 'COL1A1/COL1A2', 'IGFBP7/IGFBP5', 'TAGLN/ACTA2', 'KRT14/KRT10', 'CFD/APOD', 'DCN/CFD', 'DCD/SAT1', 'IGFBP7/SPARCL1', 'FOS/IGFBP7', 'HLA-DRA/CD74', 'IGFBP7/TAGLN', 'FOS/JUNB', 'DNAJB1/FOS']
def report(n):return json.loads((ANALYSIS/n/'report.json').read_text())
def esc(x):
 return str(x).replace('&',r'\&').replace('%',r'\%').replace('_',r'\_').replace('#',r'\#')
def historical(n):return json.loads((ROOT/'outputs'/n/'report.json').read_text())
def probability(x):return f'{float(x):.3g}' if x is not None else '—'
def f(x,n=4):return '—' if x in (None,'') else f'{float(x):.{n}f}'
def table(label,caption,headers,rows,widths):
 col='@{}'+''.join('p{'+str(w)+'mm}' for w in widths)+'@{}'
 header=' & '.join(r'\textbf{'+esc(h)+'}' for h in headers)+r' \\'
 body='\n'.join(' & '.join(esc(c) for c in row)+r' \\' for row in rows)
 # Reserve each compact table including its caption, header and wrapped rows.
 row_lines=sum(max(math.ceil(len(str(c))/max(1,w*.7)) for c,w in zip(row,widths)) for row in rows)
 reserve=min(700, 65 + 11*math.ceil(len(caption)/125) + 12*row_lines)
 prefix = (r'\Needspace{'+str(reserve)+'pt}\n') if reserve else ''
 return prefix+'\n'.join([r'{\small',r'\begin{longtable}{'+col+'}',r'\caption{'+caption+r'}\label{'+label+r'}\\',r'\toprule',header,r'\midrule\endfirsthead',r'\multicolumn{'+str(len(headers))+r'}{l}{\tablename\ \thetable\ (continued)}\\',r'\toprule',header,r'\midrule\endhead',r'\bottomrule\endfoot',body,r'\end{longtable}',r'}'])
def csvrows(n):return list(csv.DictReader((ROOT/'manuscripts/tables'/n).open()))
# Each exported table lives in TeX; no Markdown draft is used by the build.
p1=[]
p1.append(table('tab:p1patients','Author-mapped GSE165816 DFU patient scores (7 healed, 4 not healed). Each score is the mean frozen fibroblast-associated topic loading over all retained cells in the listed foot specimens; pooling cells weights repeated specimens by retained cell count. Cells are counts, not independent outcome observations. Patient identifiers are study-derived pseudonyms and G labels identify specimens. The outcome is the source-study category within 12 weeks, not an individual healing day. Scores are on the topic-loading scale from zero to one.', ['Patient','Outcome','Specimens','Cells','All-cell mean'],[[r['patient_id'].split('_')[-1],r['healing_status'].replace('_',' '),r['sample_titles'].replace('|',', '),r['n_cells'],f(r['score_cell_weighted'])] for r in csv.DictReader((ROOT/'outputs/cohort_metadata/gse165816_patient_unit_remap/patient_scores.csv').open())],[22,29,39,26,49]))
rows=csvrows('paper1_representation_inference.csv')
p1.append(table('tab:p1sampleauc',r'Exploratory discrimination across 9 healing and 5 non-healing GSE165816 specimens. AUC is the area under the ROC curve for leave-one-sample-out scores; higher values favour healing. The percentile 95\% intervals use 4,000 arm-stratified resamples of fixed out-of-fold scores. One-sided permutation probabilities and null means rerun fold-dependent orientation and fitting. PCA is principal component analysis; NMF is nonnegative matrix factorization. The frozen topic encoder itself used the discovery expression cohort. Repeated patients limit independence, and none of the six paired AUC-difference intervals excludes zero.',['Readout','AUC','Bootstrap 95% interval','Permutation p','Null mean'],[[r['readout'].replace('Fibroblast topic','Fibroblast topic'),f(r['auc'],3),f(r['ci_low'],3)+' to '+f(r['ci_high'],3),f(r['p_one_sided']),f(r['null_mean'],3)] for r in rows],[25,20,49,37,34]))
rows=csvrows('paper1_patient_unit_and_anatomy.csv')
p1.append(table('tab:p1patientauc','Patient-unit discrimination and anatomical sensitivity within GSE165816. The first four rows are leave-one-patient-out AUCs for 7 healing and 4 non-healing patients, with 4,000 arm-stratified bootstrap draws of fixed scores and one-sided label-permutation probabilities. PCA and NMF denote principal component analysis and nonnegative matrix factorization. The final row is the foot-minus-forearm all-cell fibroblast-associated topic mean difference in 10 paired patients, with a 4,000-draw paired bootstrap interval and a two-sided exhaustive sign-flip probability using add-one correction. Its Benjamini--Hochberg q value across 15 topics is 0.0402. The two row types have different estimands; neither supplies external validation.',['Readout','Estimate','Bootstrap 95% interval','Permutation p'],[[r['quantity'].replace('_',' ').replace('Fibroblast topic','Fibroblast topic'),f(r['estimate'],4),f(r['lower_95'],4)+' to '+f(r['upper_95'],4),f(r['p_value'],4)] for r in rows],[45,25,59,38]))
rows=csvrows('paper1_representation_cross_method.csv')
p1.append(table('tab:p1correlations','Spearman correlations between the four representative sample-level prediction scores across the same 14 DFU specimens (9 healing, 5 non-healing). Fibroblast topic is the frozen all-cell loading, Module the specified fibro-inflammatory score, PCA principal component analysis and NMF nonnegative matrix factorization. Each row is one pair of readouts; values are descriptive point estimates without confidence intervals or multiplicity-adjusted tests. Related scores do not establish equivalent discrimination or rank methods.',['Readout A','Readout B','Spearman correlation'],[[r['readout_a'].replace('Fibroblast topic','Fibroblast topic'),r['readout_b'].replace('Fibroblast topic','Fibroblast topic'),f(r['spearman_rho'])] for r in rows],[53,53,65]))
d=report('design_power_simulation'); rows=[]
for key,block in [('design_a_detect_difference','Detect difference'),('design_b_declare_equivalence','Equivalence under zero difference')]:
 for k,v in d[key].items():rows.append([block,k.split('_')[-1],v['total'],f"{v['n_healed']} / {v['n_not_healed']}",f(v['power'],3)])
p1.append(table('tab:p1design','Conditional next-cohort simulations for all-cell fibroblast-associated topic mean loading. Rows assume one independent patient per observation, no missing outcomes, healing allocation near 9/14, and arm SDs 0.04845 and 0.01584 estimated from discovery specimens. Two-sided Welch tests assess candidate mean differences; Welch two-one-sided tests assess equivalence under a true difference of zero, at alpha=0.05. Total and arm columns give the simulated observation counts; power uses 4,000 draws per candidate size. Values near 0.80 have Monte Carlo error and are approximate search outputs. Candidate differences and margins are inputs, not clinical minimum important differences or validated recruitment targets.',['Design','Difference / margin','Total','Healing / other','Estimated power'],rows,[50,30,20,30,35]))
# Numerical semantic and inferential control summaries, directly read from existing CSVs.
s=report('mixture_semantic_inference')
rows=csvrows('paper1_mixture_semantic_inference.csv')
p1.append(table('tab:p1semantics',r'Association between mean fibroblast-associated topic loading within fibroblasts and the threshold-defined high-state fraction across 25 GSE165816 specimens. The Spearman row gives the observed correlation and percentile 95\% limits from 10,000 sample-row bootstrap draws. The leave-one-out row gives the minimum and maximum of 25 recalculations, not a confidence interval; a dash means no single point estimate applies. A separate 10,000-draw permutation analysis gave a two-sided add-one probability of 0.00010 and a central null interval from -0.4025 to 0.4072. Samples may share patients, and the two summaries share cells.',['Summary','Estimate','Lower endpoint','Upper endpoint'],[[r['metric'].replace('_',' '),f(r['estimate']),f(r['ci_low']),f(r['ci_high'])] for r in rows],[63,28,39,37]))
# The same depth definition is used in every plotted cohort; both are tabulated.
rows=[]
d=report('external_immune_axis')
for name,c in d['cohorts'].items():
 assoc=c['sample_level_associations']
 rows.append([name,c['sample_count'],*[f(assoc[k]['rho'],3) for k in ['immune_fraction_exclusive','b_plasma_share_of_immune','median_genes_per_cell','median_umis_per_cell']]])
c=report('external_gse268834_projection');assoc=c['sample_level_associations']
rows.append(['GSE268834',8,*[f(assoc[k]['rho'],3) for k in ['immune_fraction_exclusive','b_plasma_share_of_immune','median_genes_per_cell','median_umis_per_cell']]])
p1.append(table('tab:p1external','External sample-level Spearman correlations with the frozen fibroblast fibroblast-associated topic mean under exclusive lineage gates. Immune fraction divides immune-assigned cells by all retained cells; B/plasma share divides B/plasma cells by immune-assigned cells. Detected genes and unique molecular identifiers (UMIs) are separate per-sample medians over QC cells. All entries are descriptive point estimates without confidence intervals. Specimens are not verified independent patients, and no listed cohort supplies a qualifying patient-level healing outcome.', ['Cohort','Samples','Immune fraction','B/plasma share','Detected genes','UMIs'],rows,[29,18,29,29,29,29]))

# Full exploratory covariate scan; preserve the historical rounded cut and sample unit.
d=historical('stratifier_sweep')
readable={'frac_b_plasma':'B/plasma fraction','frac_endothelial':'Endothelial fraction','frac_fibroblast':'Fibroblast fraction','frac_keratinocyte':'Keratinocyte fraction','frac_lymphatic_ec':'Lymphatic endothelial fraction','frac_mast':'Mast-cell fraction','frac_melanocyte':'Melanocyte fraction','frac_myeloid':'Myeloid fraction','frac_pericyte_smc':'Pericyte/smooth-muscle fraction','frac_sweat_gland':'Sweat-gland fraction','frac_t_cell':'T-cell fraction','tech_diss':'Fibroblast dissociation score','tech_umi':'Fibroblast median UMI count','tech_ptprc_pos':'Fibroblast PTPRC-positive fraction','meta_g_number':'Numeric G specimen label','n_cells_total':'Total retained cells','n_fibroblasts':'Retained fibroblasts'}
for i in range(1,15):readable[f'fib_mean_topic_{i}']=f'Fibroblast {TOPIC_LABELS[i]} mean'
rows=[[readable[r['covariate']],r['n'],f(r['rho']),probability(r['p']),probability(r['q_bh'])] for r in d['sweep']]
p1.append(table('tab:p1covariates',r'Complete exploratory covariate screen in 25 discovery specimens. Each row correlates the fibroblast high-state fraction, using the historical rule loading at least 0.184, with one of 31 covariates. Lineage fractions use all retained cells; technical summaries and topic means use fibroblasts. Values are Spearman rho, two-sided asymptotic p and Benjamini--Hochberg q across all 31 tests, ordered by absolute rho; 14 rows have q below 0.05. UMI means unique molecular identifier. The G label is an identifier, not an established batch or time variable. Repeated patients, shared cells and compositional constraints limit independence; these marginal associations are not causal or healing-validation tests.',['Covariate','Specimens','Spearman rho','Raw p','BH q'],rows,[76,20,25,22,22]))
d=historical('ambient_invariance')
rows=[]
for name,n,r2,b in [('Before immune-transcript exclusion',24,None,d['test_A_purity']['bimodal_all']),('After immune-transcript exclusion',24,None,d['test_A_purity']['bimodal_pure']),('Immune-covariate residuals',25,d['test_B_residual']['r2_immune_covariates'],d['test_B_residual']['bimodal_residual']),('Placebo-covariate residuals',25,d['test_B_placebo']['r2'],d['test_B_placebo']['bimodal_residual'])]:
 rows.append([name,n,f(r2),f(b['bic_1'],3),f(b['bic_2'],3),f(b['delta_bic'],3)])
p1.append(table('tab:p1ambient',r'Immune-transcript exclusion and residual-mixture controls. BIC denotes Bayesian information criterion, fitted to sample high-state fractions or their regression residuals; the difference is BIC for one Gaussian minus BIC for two. Positive differences favour two components. The first two rows share 24 matched specimens and have fraction correlation 0.9887. Residual regressions use all 25 specimens: immune covariates are B/plasma, T-cell and myeloid fractions plus immune-transcript positivity; placebos are pericyte/smooth-muscle, endothelial, melanocyte and sweat-gland fractions. R squared is variance explained by each regression and is inapplicable to unadjusted rows (dash). Both residual differences are negative, so the analysis does not establish immune-specific separation.',['Summary','n','R squared','BIC one','BIC two','Difference'],rows,[64,13,22,23,23,20]))
d=historical('celltype_resolved');rows=[]
for cohort,c in d['cohorts'].items():
 for key,name in [('composition_test','Fibroblast fraction'),('whole_sample_test','All-cell fibroblast-associated topic mean'),('within_lineage_test','Fibroblast fibroblast-associated topic mean')]:
  v=c[key];rows.append([cohort.split('_')[0],name,f(v['ratio'],3),f(v['ratio_ci95'][0],3)+' to '+f(v['ratio_ci95'][1],3),probability(v['p'])])
p1.append(table('tab:p1lineage',r'Historical sample-level lineage and loading contrasts. Ratios divide the healing-arm mean by the non-healing-arm mean; intervals are percentile 95\% limits from 20,000 within-arm sample bootstraps, and p values are two-sided Mann--Whitney tests. GSE165816 uses 9 versus 5 DFU specimens; GSE231643 uses 5 versus 3 title-labelled specimens. The discovery ratios come from the saved lineage-projection analysis and are distinct from the later deterministic all-cell patient contrast. Fibroblast fraction uses all cells as denominator; fibroblast mean uses only assigned fibroblasts. These are separate estimands. Repeated discovery patients and unavailable external patient mappings prevent independent outcome validation.',['Cohort','Readout','Mean ratio','Bootstrap 95% interval','Raw p'],rows,[29,49,24,42,21]))
readouts={'topic_simplex_theta0':'Fibroblast topic','module_score':'Module','pca':'PCA','nmf':'NMF'}
rows=[]
for name,unit in [('representation_inference','14 specimens'),('patient_unit_representation_benchmark','11 patients')]:
 for pair,v in report(name)['pairwise_auc_difference'].items():
  a,b=pair.split('__minus__');rows.append([unit,readouts[a]+' minus '+readouts[b],f(v['observed_difference']),f(v['bootstrap_95_ci'][0])+' to '+f(v['bootstrap_95_ci'][1])])
p1.append(table('tab:p1aucdifferences',r'All six paired AUC differences at each analysis unit. Each contrast subtracts the second leave-one-out readout from the first. Percentile 95\% intervals use 4,000 common-index, arm-stratified bootstrap draws of fixed out-of-fold scores: 9 versus 5 specimens or 7 versus 4 mapped patients. PCA and NMF denote principal component analysis and nonnegative matrix factorization. No sample-unit interval excludes zero; patient-unit Fibroblast topic minus NMF and Module minus NMF intervals do. The intervals are exploratory, are not adjusted across pairs, and do not refit the entire representation in each bootstrap draw.',['Unit','AUC contrast','Difference','Bootstrap 95% interval'],rows,[31,59,26,51]))
d=report('paired_anatomical_control');rows=[]
for v in d['all_topic_contrasts']:
 rows.append([TOPIC_LABELS[v['topic']],f(v['observed_difference_foot_minus_forearm']),f(v['bootstrap_95_ci'][0])+' to '+f(v['bootstrap_95_ci'][1]),probability(v['p_two_sided_exact_sign_flip']),probability(v['bh_q'])])
p1.append(table('tab:p1anatomy',r'Complete paired anatomical control across 15 topics in 10 author-mapped patients. Differences are mean all-cell loadings in foot minus forearm, after cell-count-weighted collapse of repeated foot specimens. Intervals are percentile 95\% limits from 4,000 paired-patient bootstrap draws. Two-sided p values enumerate all 1,024 sign allocations and retain add-one correction; q values use Benjamini--Hochberg across 15 topics. The TIMP1/COL3A1, COL1A1/COL1A2, CFD/APOD and IGFBP7/TAGLN loadings have q below 0.05. Labels list the two leading decoder genes; they do not assert cell-type identity. Bootstrap intervals and permutation tests need not be dual. This is an anatomical sensitivity control within the discovery source, not a healing endpoint.',['Leading genes','Foot minus forearm','Bootstrap 95% interval','Sign-flip p','BH q'],rows,[42,35,48,21,19]))
rows=[]
for unit,d in [('14 specimens',report('patient_mapping_equivalence')),('11 patients',historical('cohort_metadata/gse165816_patient_unit_remap'))]:
 for v in d['equivalence']['margins']:
  rows.append([unit,f(v['bound'],2),probability(v['p_lower']),probability(v['p_upper']),'Yes' if v['equivalent_at_alpha_0_05'] else 'No'])
p1.append(table('tab:p1equivalence',r'Complete Welch two-one-sided-test sensitivity grids for the all-cell mean fibroblast-associated topic contrast. The symmetric margin is on the loading scale, and both lower and upper one-sided p values must be below 0.05 for the final column to be Yes. Sample rows use 9 versus 5 specimens; patient rows use 7 versus 4 mapped patients with cell-count-weighted repeat collapse. Margins were examined retrospectively and have no externally justified clinical meaning. A Yes entry therefore records a mathematical sensitivity result, not demonstrated clinical equivalence.',['Unit','Margin','Lower-test p','Upper-test p','Both below 0.05'],rows,[33,23,33,33,43]))
d=historical('method_constant_sensitivity');rows=[]
for v in d['cut_sweep']['rows']:
 rows.append([f(v['cut']),f(v['A_rho_mean_vs_weight']),f(v['C_ratio'],3),probability(v['C_p']),'Healthy' if v['B_counterexample_holds'] else 'DFU'])
p1.append(table('tab:p1cuts',r'All 18 state-cut sensitivity evaluations for the frozen K=15 topic. Spearman rho correlates fibroblast mean loading with the threshold-defined high-state fraction across 25 specimens. The ratio compares mean high-state fractions in 9 healing versus 5 non-healing specimens; p is the unadjusted two-sided Mann--Whitney probability. The last column gives the group containing the largest fraction. The grid includes the fitted cut rounded to 0.1843. Four cuts have p below 0.05; these are dependent sensitivity analyses, not 18 independent confirmations.',['State cut','Semantic rho','Healing / non-healing','Raw p','Largest fraction'],rows,[27,31,43,25,39]))
rows=[]
for v in d['k_sweep']['rows']:
 rows.append([v['K'],'IGFBP-rich' if v['K']==10 else 'CHI3L1/COL3A1-rich',f(v['derived_cut']),f(v['A_rho_mean_vs_weight']),probability(v['C_p']),'Yes' if v['B_counterexample_holds'] else 'No'])
p1.append(table('tab:p1capacity',r'Topic-capacity sensitivity after tracking the TIMP1-carrying topic at each K. Gene-based descriptions identify the tracked loading; each fit supplies its own two-Gaussian midpoint cut. Semantic rho uses 25 specimens; the unadjusted healing-arm p value uses 9 versus 5 high-state-fraction summaries. The final column asks whether the maximum fraction occurs in healthy skin. At K=10 the tracked topic is a different IGFBP-rich programme and the counterexample fails. Topics across capacities are not assumed to have identical biological meaning.',['K','Programme description','Derived cut','Semantic rho','Healing p','Healthy maximum'],rows,[12,46,25,26,21,35]))
d=report('design_power_simulation');rows=[]
for key,v in d['design_c_resolve_auc_difference'].items():
 rows.append([key.split('_')[-1],v['total'],f"{v['n_healed']} / {v['n_not_healed']}",f(v['power'],3)])
p1.append(table('tab:p1aucdesign',r'Exploratory binormal planning simulation for paired AUC differences. Two candidate AUCs are centred on 0.80, separated by the stated gap, with within-class score-noise correlation 0.5022 and healing allocation near 9/14. Each searched total uses 4,000 simulation draws and a model-based normal approximation for the paired difference at alpha=0.05. Totals assume one observation per independent patient and no missing outcome. The gaps are hypothetical inputs; the approximate 80\% power search does not establish actual clinical performance, calibrated patient-test power or a validated recruitment target.',['Candidate AUC gap','Total observations','Healing / non-healing','Estimated power'],rows,[44,38,51,34]))

# Keep design simulations together and end with the full threshold grid.
p1.insert(5, p1.pop())
p1[-2], p1[-1] = p1[-1], p1[-2]

r=json.loads((ROOT/'outputs/robustness_extensions/report.json').read_text())['patient']
a=r['patient_semantics'];b=r['patient_outcome_influence']
rows=[['Mean versus high-state fraction','20 patients',f(a['rho']),f(a['bootstrap_95_interval'][0])+' to '+f(a['bootstrap_95_interval'][1]),f(a['omission_range'][0])+' to '+f(a['omission_range'][1])],['Healing minus non-healing','11 patients',f(b['observed_difference']),'Not recalculated',f(b['omission_range'][0])+' to '+f(b['omission_range'][1])]]
p1.insert(-2,table('tab:p1robustness',r'Patient-level robustness in the discovery cohort. The first row correlates fibroblast mean loading with the high-state fraction after weighting repeated specimen summaries by fibroblast count within 20 patients (25 specimens). Its percentile 95\% interval uses 10,000 patient resamples, seed 217. The second row uses the previously defined all-cell healing contrast in 7 healing and 4 non-healing patients; its original interval remains in the outcome table. Omission ranges give the minimum and maximum after deleting one patient at a time (20 or 11 omissions), not confidence limits. Neither analysis refits the expression model, changes the state cut, adds patients, or provides external validation.',['Quantity','Unit','Estimate','Patient bootstrap 95%','Patient-omission range'],rows,[43,24,21,39,39]))
(HERE/'paper1_tables.tex').write_text('\n\n'.join(p1)+'\n')
p2=[]
h=report('human_temporal_flow');d=report('donor_transfer_flow')
rows=[['Pooled time holdout',f(h['all_donors']['standstill']),f(h['all_donors']['predicted']),f(h['all_donors']['noise_floor']),f(h['all_donors']['improvement']*100,2)+'%']]
for name,v in h['leave_one_donor_out'].items():rows.append(['Drop '+name+'; retained pair',f(v['standstill']),f(v['predicted']),f(v['noise_floor']),f(v['improvement']*100,2)+'%'])
for name,v in d['per_donor'].items():rows.append([name+' transfer',f(v['ed_standstill']),f(v['ed_predicted']),f(v['noise_floor']),f(v['improvement']*100,2)+'%'])
p2.append(table('tab:p2folds','Human Wound7 evaluation in GSE241132. ED denotes the empirical energy-distance V-statistic in training-standardized latent space; lower values indicate closer predicted and observed distributions. The pooled row excludes Wound7 globally. Drop-one rows exclude the named donor and evaluate pooled Wound7 only in the two retained donors. Transfer rows instead evaluate the excluded donor after fitting all four time points of the other donors. Improvement is 100 times (stay-still ED minus predicted ED) divided by stay-still ED. Split-half ED uses one seeded target split and is not a confidence limit. Every row is a point estimate; these dependent fits do not create additional donors.',['Evaluation','Stay-still ED','Predicted ED','Split-half ED','Improvement'],rows,[50,28,28,28,31]))
d=report('time_parameterisation')
rows=[[n.replace('_',' '),f(v['t_holdout']),f(v['ed_at_claimed']),f(v['improvement_at_claimed']*100,2)+'%',str(v['diverged'])] for n,v in d['axes_results'].items()]
p2.append(table('tab:p2axes','Four time coordinates under global Wound7 holdout. The reference distance is '+f(d['standstill'])+' and the split-half distance is '+f(d['noise_floor'])+'. ED denotes empirical energy distance in training-standardized latent space. Wound7 time is the global transformed coordinate; the reported target distance is evaluated at the nearest point of the 60-step Wound1-to-Wound30 scan. Improvement is 100 times the gain divided by stay-still distance. Rows use the same three donors, with Wound7 excluded globally; the path minimum is not substituted for target error, and no interval is shown.',['Time coordinate','Wound7 time','Target ED','Improvement','Diverged'],rows,[41,32,31,32,29]))
d=report('donor_conditioned_benchmark')
names={'M0_standstill':'Stay-still','M1_shared_cfm':'Shared CFM','M2_mean_displacement':'Mean displacement','M3_nearest_donor':'Nearest donor','M4_conditioned_cfm':'Conditioned CFM','M5_optimal_transport':'Entropic OT extension'}
rows=[[names[m],f(v['mean_ed']),f(v['mean_gain']),f"{v['n_pass']}/{v['n']}"] for m,v in d['summary'].items()]
p2.append(table('tab:p2methods','Common Wound1-to-Wound7 benchmark across the three held-out human donors. ED is empirical energy distance in each training-standardized fold; reported means equally weight donors. Gain is stay-still ED minus method ED. Pass count records gains above the single split-half target reference, a descriptive criterion rather than a significance test. CFM denotes conditional flow matching and OT the entropic optimal-transport displacement extension. All methods share test donors; point estimates without confidence intervals do not establish a population ranking.',['Method','Mean ED','Mean gain','Pass count'],rows,[68,34,34,31]))
rows=[]
for m,vs in d['per_donor'].items():rows.append([names[m],*[f(vs[n]['ed']) for n in ['PWH26','PWH27','PWH28']]])
p2.append(table('tab:p2methodsbydonor','Empirical energy distances for each method and held-out human donor in the common benchmark. Each column uses the other two donors for fitting and scaling, the named donor\'s Wound1 cells as source and its Wound7 cells only for evaluation. Lower is better; stay-still retains the source distribution. CFM means conditional flow matching; OT is the entropic transport displacement extension. Entries are point estimates with a 1,200-cell distance cap. Training draws and this cap differ from separately run transfer experiments, so those point estimates need not coincide.',['Method','PWH26','PWH27','PWH28'],rows,[68,34,34,31]))
d=report('donor_curve_inference')
rows=[[r['held_out_donor'],f(r['k1_mean_ed']),f(r['k2_mean_ed']),f(r['mean_reduction'])] for r in d['held_out_donor_summary']]
p2.append(table('tab:p2curve',r'Seed-averaged donor-count comparison for shared flow matching. ED is empirical energy distance and k is the number of training donors. At k=1, the two single-training-donor choices are averaged within each held donor and seed; each row then averages seeds 0, 1 and 2. Reduction is k=1 ED minus k=2 ED. The equally weighted mean reduction is 0.1655, with a 4,000-draw percentile 95\% interval [0.0813, 0.3146] from three held-donor blocks. Training sets overlap; this descriptive interval is not a population coverage guarantee or evidence of a learning-curve plateau.',['Held donor','k=1 ED','k=2 ED','Reduction'],rows,[53,38,38,38]))
d=report('mouse_all_arms_pod7_audit')
rows=[[n,f(v['energy_distance_standstill']),f(v['energy_distance_predicted']),f(100*v['improvement_fraction'],2)+'%', 'Yes' if v['holdout_on_direct_path'] else 'No'] for n,v in d['arms'].items()]
p2.append(table('tab:p2mouse','Mouse POD7 audit for the source-labelled NDB, PDB and GDB arms. Each field uses rank time and POD0, POD2 and POD30 for fitting/scaling, then predicts from POD2 to excluded POD7. ED is empirical energy distance; improvement is 100 times (stay-still ED minus predicted ED) divided by stay-still ED. Each arm covers 4,182/7,002 human-panel genes and has one animal per time point. The ordering check asks whether endpoint distance is at least both endpoint-to-target distances; it is not proof of a geodesic. Values have no confidence intervals, and cell counts do not provide animal replication.',['Arm','Stay-still ED','Predicted ED','Improvement','Ordering check'],rows,[22,36,36,34,37]))
rows=csvrows('paper2_donor_geometry_inference.csv')
p2.append(table('tab:p2geometrytable',r'Descriptive geometry for three healthy acute-wound donors. The first estimate divides the median of 18 within-donor between-time energy distances by the median of 12 between-donor same-time distances. The second is the mean of three pairwise cosines between donor Wound1-to-Wound7 mean-displacement vectors. Endpoints are percentile 95\% limits from 10,000 resamples of pairwise distances within class or of cosine pairs. Pairs share donors, so these intervals do not provide independent donor replication or a general population ordering.',['Summary','Estimate','Lower endpoint','Upper endpoint'],[[r['metric'].replace('_',' '),f(r['estimate']),f(r['ci_low']),f(r['ci_high'])] for r in rows],[72,30,33,32]))

d=report('donor_conditioned_benchmark')
rows=[[key.split('/')[0],key.split('/')[1],f(v['standstill']),f(v['shared']),f(v['conditioned'])] for key,v in d['in_sample'].items()]
p2.append(table('tab:p2insample',r'All six training-donor comparisons for shared and donor-conditioned flow matching. The first column identifies the donor excluded from that fit; the second is a retained training donor whose Wound1-to-Wound7 prediction is evaluated. ED is empirical energy distance in the fold-standardized coordinates. Both source and target of the evaluated donor were available during fitting, so these are fitting-capacity comparisons rather than donor-transfer tests. Conditioned errors are lower in all six rows. The repeated use of three donors prevents interpreting the rows as six independent biological replicates.',['Excluded donor','Evaluated training donor','Stay-still ED','Shared ED','Conditioned ED'],rows,[32,47,29,27,30]))
d=report('donor_curve_seed_stability');c=report('donor_count_curve');rows=[]
for seed,v in d['per_seed'].items():rows.append(['Shared CFM',seed,f(v['k1_mean_ed']),f(v['k2_mean_ed']),f(v['reduction_k1_to_k2'])])
rows.append(['Mean displacement','0',f(c['curve']['k_1']['mean_displacement_mean_ed']),f(c['curve']['k_2']['mean_displacement_mean_ed']),f(c['step_one_to_two_donors']['mean_displacement_ed_reduction_k1_to_k2'])])
p2.append(table('tab:p2seedcurve',r'Donor-count means by training seed and non-neural control. CFM denotes conditional flow matching, ED empirical energy distance and k the number of training donors. At k=1, two available single-donor fits are averaged within held donor; at k=2 one fit uses both available donors. Means then equally weight the three held donors. Reduction is k=1 minus k=2. CFM evaluation subsamples are fixed across seeds 0, 1 and 2; the mean-displacement control is recorded at seed 0. All nine CFM runs per seed and all six/three control runs at k=1/k=2 meet the descriptive split-half criterion. The control also improves with a second donor.',['Predictor','Seed','k=1 mean ED','k=2 mean ED','Reduction'],rows,[49,17,35,35,29]))
rows=[[v['held_out_donor'],', '.join(v['training_donors']),v['k'],f(v['mean']),f(v['sd']),f(v['range'])] for v in d['training_stochasticity']['per_cell']]
p2.append(table('tab:p2seedconfigs',r'Training stochasticity for every held-donor/training-subset configuration. Mean ED, sample SD and range summarize the same fit repeated at seeds 0, 1 and 2; range is maximum minus minimum. Evaluation subsampling and the target split are fixed, so variation reflects training randomness. Averaging the nine configuration SDs gives 0.0717, 3.13 times the mean split-half reference 0.0229; the maximum range is 0.3683. Seeds and overlapping subsets are not independent donors and the single split-half criterion omits this training variability.',['Held donor','Training donors','k','Mean ED','SD','Range'],rows,[28,53,12,26,23,23]))
d=report('mouse_all_arms_pod7_audit');rows=[]
for name,v in d['arms'].items():rows.append([name,*[v['n_cells_by_pod'][t] for t in ['POD0','POD2','POD7','POD30']],f(v['energy_distance_noise_floor'],5)])
p2.append(table('tab:p2mousecounts',r'Fibroblast cell counts and target-sampling reference for each mouse arm. POD means postoperative day. POD0, POD2 and POD30 enter training; POD7 is the held-out target. Every arm/timepoint cell group comes from one animal, so these counts quantify distribution sampling and not biological replication. The final column is one seeded split-half POD7 energy distance in the training-standardized space. NDB, PDB and GDB are retained source-study arm labels. All arms share 4,182/7,002 mapped panel genes.',['Arm','POD0','POD2','POD7 held out','POD30','Split-half ED'],rows,[21,27,27,34,27,29]))

# Place mouse cell counts beside the mouse errors; end with all seed configurations.
p2.insert(6, p2.pop())

r=json.loads((ROOT/'outputs/robustness_extensions/report.json').read_text())['temporal']
rows=[[v['rk4_steps'],f(v['energy_distance'],9),f(100*v['relative_improvement'],6)+'%',f"{v['rms_coordinate_difference_from_200']:.3g}"] for v in r['numerical_sensitivity']['rows']]
p2.append(r'\Needspace{330pt}'+'\n'+table('tab:p2numerics',r'Fixed-field Runge--Kutta resolution comparison for pooled day-7 holdout. A single seed-0 field was refitted with the specified 8,000 optimization steps and 256-cell batches on the saved expression coordinates, excluding day 7 from fitting and scaling. All rows use the same 1,012 day-1 cells and the same 1,500 sampled target cells. Energy distance is the empirical V-statistic evaluated in double precision; improvement is relative to the same unchanged-source baseline (1.406924). RMS is the root-mean-square coordinate difference from the 200-step solution; it is a numerical discrepancy, not a confidence interval. The comparison is conditional on one field and finite-precision arithmetic and does not establish formal convergence to an exact ODE solution.',['RK4 steps','Energy distance','Improvement','RMS vs 200 steps'],rows,[28,46,44,48]))
rows=[[v['cells_per_distribution'],v['draws'],f(100*v['median_relative_improvement'],2)+'%',f(100*v['central_95_draw_range'][0],2)+' to '+f(100*v['central_95_draw_range'][1],2)+'%',str(v['gain_exceeds_split_half_count'])+'/'+str(v['draws'])] for v in r['evaluation_sampling']['summary']]
p2.append(table('tab:p2sampling',r'Evaluation-sampling sensitivity for the same fixed field with 50 RK4 steps. For each cell count, 50 seeded draws sample source and target cells without replacement; prediction and unchanged-source comparisons use identical source indices and identical target indices within a draw. An additional pair of disjoint target subsets at that count defines a split-half reference. Percentages summarize relative improvement over unchanged source; the central 95\% draw range measures Monte Carlo sensitivity conditional on this cohort and field, not patient-level confidence. The final column counts draws whose gain exceeds the split-half reference. Cell count and resampling do not increase the three-donor biological sample size.',['Cells per distribution','Draws','Median improvement','Central 95% draw range','Gain exceeds reference'],rows,[34,17,37,42,37]))
(HERE/'paper2_tables.tex').write_text('\n\n'.join(p2)+'\n')
print('Exported supplementary numerical tables from reports without fitting models.')
